# -*- coding: utf-8 -*-
"""csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMlphCB43WLHxzp-rzVLWeP5bWbXTTfg
"""

import pandas as pd
data=pd.read_csv("/content/Book1.csv")
print(data)

tips=sns.load_dataset("tips")
daily_total_bill=tips.groupby("day")["total_bill"].sum().reset_index()
print(daily_total_bill)
plt.bar(daily_total_bill["day"],daily_total_bill["total_bill"])
plt.xlabel("Day of the week")
plt.ylabel("Total Bill amount")
plt.title("Total Bill Amount by Day")
plt.show()





from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

import numpy as np  # Import the NumPy library and give it the alias 'np'

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(np.__version__)

import numpy as np
arr=np.array([1,2,3,4,5])
print(np.sum(arr))

import panadas as pd
df = pd.DataFrame([[2,3,4],
                  [12,13,14],
                  [44,45,46]],
                  columns=['english','maths',
                          'sciences','socail'])
print(df)

import pandas as pd
data=pd.read_csv("/content/tips.csv")
print(data)

total=data.groupby('day')['total_bill'].sum()
print(total)

filter=data[data['tip']>5]
print(filter)

import pandas as pd
from functools import reduce

# Load the data again (assuming 'tips.csv' is available)
data = pd.read_csv("/content/tips.csv")

total_tip = reduce(lambda x, y: x + y, data['tip'])
print(total_tip)

import pandas as pd
data=pd.read_csv ("")

import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
c=a[~a.isin(b)]
d=b[~b.isin(a)]
print(c)
print(d)
print(a.min())
print(b.sum())
average=sum(a)/len(a)
print(average)
print(b.median())

import matplotlib.pyplot as plt
categories=['A','B','C','D']
amout=[200,300,400,500]
plt.bar(categories,amout)
plt.xlabel('categories')
plt.ylabel('amout')
plt.title("the bar graph")
plt.show



import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
c=a[~a.isin(b)]
d=b[~b.isin(a)]
print(c)
print(d)
print(a.min())
print(b.sum())
average=sum(a)/len(a)
print(average)
print(b.median())

import pandas as pd
df=pd.DataFrame([30,60,80,90])

import pandas as pd
data={'name':['pooja','shravanika','anikata','lacchi'],
   'subname':['english','kannda','physic','chemistry'],
   'marks':[50,99,89,40]}
df=pd.DataFrame(data)
print(df)

import pandas as pd
df=pd.DataFrame({'emp_id':[56,78,90,56]})

name=df.groupby('sub')
data

name=df.groupby('subname')
data